### ISSUE TITLE
Attempt to invoke interface method 'PresenterFactory.create()' on a null object reference`

### ISSUE THREAD

**Issue by alouanemed** [czyrux/MvpLoaderSample#9]
Hey,

I ve implemented your simple in to an app, when launching the app I am getting this error : 
```

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'presenter.BasePresenter presenter.loader.PresenterFactory.create()' on a null object reference`
at presenter.loader.PresenterLoader.onForceLoad(PresenterLoader.java:39)
at android.support.v4.content.Loader.forceLoad(Loader.java:329)
```
in this line in particular 
`        mPresenter = mPresenterFactory.create();`

I am using dagger 2 to inject the presenter factory inside the presenter

**Comment by czyrux** [comment]
Can you show me more code, what are you injecting in the Fragment, the Presenter or the Factory?

**Comment by czyrux** [comment]
Closing until I can get further details
